# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='preguntas',
            name='idp',
            field=models.IntegerField(default=1),
        ),
    ]
