# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-16 02:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intercambio', '0002_preguntas_idp'),
    ]

    operations = [
        migrations.AddField(
            model_name='puntajes',
            name='tf',
            field=models.CharField(default=b'<function now at 0x7fd83ab89398>', max_length=50),
        ),
    ]
